river:
  build: .
  volumes: ./code
  command: python main/main.py
  links:
    - es
    - db
kibana:
  image: kibana
  ports:
    - '5601:5601'
  links:
    - es
db:
  image: mysql
  ports:
    - '3306:3306'
es:
  image: elasticsearch
  ports:
    - '9002:9002'


